In [2]:
# graficos embebidos
%matplotlib inline

In [3]:
# importando pandas, numpy y matplotlib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# importando los datasets de sklearn
from sklearn import datasets

boston = datasets.load_boston()
boston_df = pd.DataFrame(boston.data, columns=boston.feature_names)
boston_df['TARGET'] = boston.target
boston_df.head() # estructura de nuestro dataset.

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,TARGET
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2

In [4]:
# importando el modelo de regresión lineal
from sklearn.linear_model import LinearRegression

rl = LinearRegression() # Creando el modelo.
rl.fit(boston.data, boston.target) # ajustando el modelo

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [5]:
# Lista de coeficientes B para cada X
list(zip(boston.feature_names, rl.coef_))

[('CRIM', -0.10717055656035383),
 ('ZN', 0.046395219529801815),
 ('INDUS', 0.020860239532171893),
 ('CHAS', 2.6885613993179547),
 ('NOX', -17.795758660309019),
 ('RM', 3.8047524602580012),
 ('AGE', 0.00075106170332062128),
 ('DIS', -1.4757587965198176),
 ('RAD', 0.30565503833909746),
 ('TAX', -0.012329346305271827),
 ('PTRATIO', -0.95346355469055832),
 ('B', 0.0093925127221892168),
 ('LSTAT', -0.52546663290078932)]

In [6]:
# haciendo las predicciones
predicciones = rl.predict(boston.data)
predicciones_df = pd.DataFrame(predicciones, columns=['Pred'])
predicciones_df.head() # predicciones de las primeras 5 lineas

        Pred
0  30.008213
1  25.029861
2  30.570232
3  28.608141
4  27.942882

In [7]:
# Calculando el desvio
np.mean(boston.target - predicciones)

7.5688247939662851e-15